context("gate")

test_that("gates allow simple 'atomic' types, if prototypes match", {
    expect_true(gate(TRUE, logical(1L)))
    expect_true(gate(1L, integer(1L)))
    expect_true(gate(1, double(1L)))
    expect_true(gate(1, numeric(1L)))
    expect_true(gate(1+2i, complex(1L)))
    expect_true(gate("A", character(1L)))
    expect_true(gate(charToRaw("x"), raw(1L)))
    expect_true(gate(NULL, NULL))
    expect_true(gate(list("A"), list(1L)))
})

test_that("gates allow items > 0 length when prototypes are length zero", {
    expect_true(gate(rep(TRUE, 3), logical(0L)))
    expect_true(gate(rep(1L, 3), integer(0L)))
    expect_true(gate(rep(1, 3), double(0L)))
    expect_true(gate(rep(1, 3), numeric(0L)))
    expect_true(gate(rep(1+2i, 3), complex(0L)))
    expect_true(gate(rep("A", 3), character(0L)))
    expect_true(gate(rep(charToRaw("x"), 3), raw(0L)))
    expect_true(gate(list("A", "B", "C"), list()))
})

test_that("gates do not allow items when length does not match", {
    expect_false(gate(rep(TRUE, 3), logical(1L)))
    expect_false(gate(rep(1L, 3), integer(1L)))
    expect_false(gate(rep(1, 3), double(1L)))
    expect_false(gate(rep(1, 3), numeric(1L)))
    expect_false(gate(rep(1+2i, 3), complex(1L)))
    expect_false(gate(rep("A", 3), character(1L)))
    expect_false(gate(rep(charToRaw("x"), 3), raw(1L)))
    expect_false(gate(list("A", "B", "C"), list("X")))
})
